[project]
name = "zenith-client"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "click>=8.5.0",
    "configomatic[yaml]>=0.4.0",
    "pydantic<3",
    "requests>=2.34.2",
]

[project.scripts]
zenith-client = "zenith.client.cli:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.1+unknown"

[tool.hatch.build.targets.sdist]
packages = ["zenith"]
[tool.hatch.build.targets.wheel]
packages = ["zenith"]
