{
 "title": "Zenith / Services",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Reserved subdomains",
   "type": "stat",
   "description": "The number of reserved subdomains. Zenith does not currently release subdomains, so this is the number of subdomains that have ever been used for a Zenith service.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(zenith_service_initialised) by(service_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active services",
   "type": "stat",
   "description": "The active services, i.e. services with at least one active endpoint.",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(zenith_service_client_status) by(service_name) == bool ignoring(status) zenith_service_client_status{status=\"passing\"}) or vector(0)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(sum(zenith_service_client_status{status!=\"passing\"}) by(service_name) > bool 0) or vector(0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Helm releases",
   "type": "stat",
   "description": "The number of Helm releases for Zenith services that exist, in any state.",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zenith_service_helm_status{status=\"deployed\"}) or vector(0)",
     "legendFormat": "Deployed"
    },
    {
     "expr": "count(zenith_service_helm_status{status!=\"deployed\"}) or vector(0)",
     "legendFormat": "Not deployed"
    }
   ]
  },
  {
   "title": "Clients by status",
   "type": "bargauge",
   "description": "The number of clients in each status.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zenith_service_client_status{status=\"passing\"}) or vector(0)",
     "legendFormat": "passing"
    },
    {
     "expr": "sum(zenith_service_client_status{status=\"critical\"}) or vector(0)",
     "legendFormat": "critical"
    },
    {
     "expr": "sum(zenith_service_client_status{status=\"warning\"}) or vector(0)",
     "legendFormat": "warning"
    },
    {
     "expr": "sum(zenith_service_client_status{status=\"maintenance\"}) or vector(0)",
     "legendFormat": "maintenance"
    }
   ]
  },
  {
   "title": "Helm releases by status",
   "type": "bargauge",
   "description": "Shows the number of Helm releases in each status.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zenith_service_helm_status{status=\"deployed\"}) or vector(0)",
     "legendFormat": "deployed"
    },
    {
     "expr": "sum(zenith_service_helm_status{status=\"failed\"}) or vector(0)",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(zenith_service_helm_status{status=\"pending-install\"}) or vector(0)",
     "legendFormat": "pending-install"
    },
    {
     "expr": "sum(zenith_service_helm_status{status=\"pending-upgrade\"}) or vector(0)",
     "legendFormat": "pending-upgrade"
    },
    {
     "expr": "sum(zenith_service_helm_status{status=\"pending-rollback\"}) or vector(0)",
     "legendFormat": "pending-rollback"
    },
    {
     "expr": "sum(zenith_service_helm_status{status=\"uninstalling\"}) or vector(0)",
     "legendFormat": "uninstalling"
    },
    {
     "expr": "sum(zenith_service_helm_status{status=\"uninstalled\"}) or vector(0)",
     "legendFormat": "uninstalled"
    },
    {
     "expr": "sum(zenith_service_helm_status{status=\"superseded\"}) or vector(0)",
     "legendFormat": "superseded"
    },
    {
     "expr": "sum(zenith_service_helm_status{status=\"unknown\"}) or vector(0)",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Active services",
   "type": "table",
   "description": "Details of the currently active Zenith services.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(zenith_service_client_status) by(service_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(zenith_service_client_status) by(service_name) == bool ignoring(status) zenith_service_client_status{status=\"passing\"}) or (sum(zenith_service_client_status{status!=\"passing\"}) by(service_name) == bool 0)",
     "legendFormat": "__auto"
    },
    { "expr": "zenith_service_helm_status", "legendFormat": "__auto" }
   ]
  }
 ]
}