# Configuration for the Zenith client
zenithClient:
  # Indicates if the Zenith client should be in debug mode
  debug: false
  # The base64-encoded SSH private key data for the client
  # The SSH key should already be associated with a Zenith subdomain
  sshPrivateKeyData:
  # Configuration for the Zenith server
  server:
    host:
    port: 22
  # Configuration for the liveness check
  livenessCheck:
    # This should remove a dead API server from the load-balancer within 15s
    period: 5
    failures: 3
  # The image to use for the Zenith client container
  image:
    repository: ghcr.io/azimuth-cloud/zenith-client
    pullPolicy: IfNotPresent
    tag: ""  # Defaults to appVersion if not given

mitmProxy:
  # The port that the proxy is listening on
  # It should listen to localhost only on plain http
  port: 8080
  # The image to use for the proxy container
  image:
    repository: ghcr.io/azimuth-cloud/zenith-proxy
    pullPolicy: IfNotPresent
    tag: ""  # Defaults to appVersion if not given

imagePullSecrets: []
