{{- define "zenith.registrar.defaults" -}}
reservedSubdomains:
  {{- range .Values.registrar.config.reservedSubdomains }}
  - {{ tpl . $ }}
  {{- end }}
  - {{ tpl .Values.registrar.ingress.subdomain . }}
consulAddress: {{ tpl .Values.common.consul.address . | quote }}
consulPort: {{ .Values.common.consul.port }}
consulKeyPrefix: {{ .Values.common.consul.registrarKeyPrefix | quote }}
crdTargetNamespace: {{ .Values.common.kubernetes.targetNamespace }}
{{- end }}

{{- if .Values.registrar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith.componentname" (list . "registrar-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "registrar-conf") | nindent 4 }}
stringData:
  registrar.yaml: |
    {{-
      tpl (omit .Values.registrar.config "reservedSubdomains" | toYaml) . |
        fromYaml |
        mergeOverwrite (include "zenith.registrar.defaults" . | fromYaml) |
        toYaml |
        nindent 4
    }}
{{- end }}
