{{- if .Values.registrar.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zenith.componentname" (list . "registrar") }}
  labels: {{ include "zenith.componentLabels" (list . "registrar") | nindent 4 }}
{{- end }}
