name: Generate SemVer version
description: >
  Generates a SemVer-compatible version for the current commit using a combination
  of the last tag, the distance from that tag and the name of the branch that the
  commit is on.
outputs:
  version:
    description: The SemVer-compatible version for the current commit.
  short-sha:
    description: The short (7-character) SHA for the current commit.
runs:
  using: docker
  image: Dockerfile
