[project]
name = "zenith-sshd"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "click>=8.5.0",
    "configomatic[yaml]>=0.4.0",
    "cryptography>=50.0.1",
    "easykube>=0.6.0",
    "pydantic<3",
    "requests>=2.34.2",
]

[project.scripts]
consul = "zenith.sshd.backends.consul:Backend"
crd    = "zenith.sshd.backends.crd:Backend"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.1+unknown"

[tool.hatch.build.targets.sdist]
packages = ["sshd"]
[tool.hatch.build.targets.wheel]
packages = ["sshd"]
