---

version: 2

updates:
  # Automatically propose PRs for out-of-date GitHub actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      # Check for new versions weekly
      interval: weekly
    # Update all actions in a single PR
    groups:
      github-actions:
        patterns: ["*"]
    labels:
      - automation
      - gha-update

  # Automatically propose PRs for Python dependencies for each component
  - package-ecosystem: pip
    directory: "/client"
    schedule:
      # Check for new versions daily
      interval: daily
    groups:
      pip-updates:
        patterns: ["*"]
    labels:
      - automation
      - pip-update
      - client
    commit-message:
    # Prefix all commit messages with "pip: "
      prefix: "pip"

  - package-ecosystem: pip
    directory: "/operator"
    schedule:
      # Check for new versions daily
      interval: daily
    groups:
      pip-updates:
        patterns: ["*"]
    labels:
      - automation
      - pip-update
      - operator
    commit-message:
    # Prefix all commit messages with "pip: "
      prefix: "pip"

  - package-ecosystem: pip
    directory: "/registrar"
    schedule:
      # Check for new versions daily
      interval: daily
    groups:
      pip-updates:
        patterns: ["*"]
    labels:
      - automation
      - pip-update
      - registrar
    commit-message:
    # Prefix all commit messages with "pip: "
      prefix: "pip"

  - package-ecosystem: pip
    directory: "/sshd"
    schedule:
      # Check for new versions daily
      interval: daily
    groups:
      pip-updates:
        patterns: ["*"]
    labels:
      - automation
      - pip-update
      - sshd
    commit-message:
    # Prefix all commit messages with "pip: "
      prefix: "pip"

  - package-ecosystem: pip
    directory: "/sync"
    schedule:
      # Check for new versions daily
      interval: daily
    groups:
      pip-updates:
        patterns: ["*"]
    labels:
      - automation
      - pip-update
      - sync
    commit-message:
    # Prefix all commit messages with "pip: "
      prefix: "pip"
