ignore:
  # CVE in grpc package used by gomplate, we only use
  # gomplate to template out files based on local env vars
  # rather than remote datasources so shouldn't affect us
  - vulnerability: GHSA-p77j-4mvh-x3m3
    package:
      location: "/usr/bin/gomplate"

