apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clients.{{ settings.api_group }}
spec:
  group: {{ settings.api_group }}
  scope: Namespaced
  names:
    plural: clients
    kind: Client
    categories:
      - zenith
  versions:
    - name: v1alpha1
      deprecated: false
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          {{ models.v1alpha1.Client.schema() | toyaml | indent(10) }}
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Upstream Service
          type: string
          jsonPath: .spec.upstream.serviceName
        - name: MITM Enabled
          type: boolean
          jsonPath: .spec.mitmProxy.enabled
        - name: MITM Auth
          type: string
          jsonPath: .spec.mitmProxy.authInject.type
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
