apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: reservations.{{ settings.api_group }}
spec:
  group: {{ settings.api_group }}
  scope: Namespaced
  names:
    plural: reservations
    kind: Reservation
    categories:
      - zenith
  versions:
    - name: v1alpha1
      deprecated: false
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          {{ models.v1alpha1.Reservation.schema() | toyaml | indent(10) }}
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Secret
          type: string
          jsonPath: .spec.credentialSecretName
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: FQDN
          type: string
          jsonPath: .status.fqdn
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
