{{-
  if and
    (mustRegexMatch "^https?$" .Values.protocol)
    .Values.global.secure
    .Values.ingress.enabled
    .Values.ingress.tls.clientCA
}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-client-cert" .Release.Name }}
  labels: {{ include "zenith-service.labels" . | nindent 4 }}
spec:
  passTLSClientCert:
    pem: true
{{- end }}
