{{- if .Values.metrics.enabled -}}
# This role allows the holder to list secrets in the Zenith target namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zenith.componentname" (list . "helm-exporter") }}
  labels: {{ include "zenith.componentLabels" (list . "helm-exporter") | nindent 4 }}
  namespace: {{ .Values.common.kubernetes.targetNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
{{- end }}
