{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zenith.componentname" (list . "helm-exporter") }}
  labels: {{ include "zenith.componentLabels" (list . "helm-exporter") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9571
      targetPort: http
      protocol: TCP
  selector: {{ include "zenith.componentSelectorLabels" (list . "helm-exporter") | nindent 4 }}
{{- end }}
