{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zenith.componentname" (list . "helm-exporter") }}
  labels: {{ include "zenith.componentLabels" (list . "helm-exporter") | nindent 4 }}
{{- end }}
