# The ingress configuration can also from from globals
# This is mainly to reduce duplication when integrating with Azimuth
# In the future, other consumers could adopt the same conventions to reduce duplication when defining ingress
global:
  ingress:
    # The base domain to use for services exposed by Zenith
    # Proxied services will be made available at <subdomain>.<base domain>
    baseDomain:
    # The ingress class to use
    className: nginx
    # The common annotations for all ingress resources
    annotations: {}
    # The TLS configuration
    tls:
      # Indicates if TLS should be enabled
      enabled: true
      # The name of a secret containing a wildcard certificate
      secretName:
      # TLS-specific annotations for ingress resources
      annotations: {}

# Common configuration
common:
  # Ingress configuration
  # This overrides global.ingress, and can be overridden by component-specific settings
  ingress: {}
  # Consul configuration
  consul:
    # The address of the Consul server
    address: "{{ .Release.Name }}-consul-server"
    # The port of the Consul server
    port: 8500
    # The tag to use for identifying Zenith services in Consul
    serviceTag: "zenith-service"
    # The prefix to use for additional service information for Zenith services in Consul KV
    serviceKeyPrefix: "zenith/services"
    # The prefix to use for registrar information in Consul KV
    registrarKeyPrefix: "zenith"
  # Common Kubernetes configuration
  kubernetes:
    # The target namespace for Zenith services
    targetNamespace: zenith-services

sync:
  enabled: true
  # Configuration for the sync component
  config:
    kubernetes:
      ingress: {}
  # The image to use for the sync component
  image:
    repository: ghcr.io/stackhpc/zenith-sync
    pullPolicy: IfNotPresent
    tag: ""  # Defaults to appVersion if not given
  imagePullSecrets: []
  # Customise pod-level security context for sync pods
  podSecurityContext:
    runAsNonRoot: true
  # Customise container-level security context for sync pods
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
  # Resources for sync containers
  resources: {}
  # Customise annotations for sync pods
  podAnnotations: {}
  # Customise node selector for sync pods
  nodeSelector: {}
  # Customise tolerations for sync pods
  tolerations: []
  # Customise affinity rules for sync pods
  affinity: {}

sshd:
  enabled: true
  # Config for the SSHD server
  config: {}
  # The image to use for the SSHD server
  image:
    repository: ghcr.io/stackhpc/zenith-sshd
    pullPolicy: IfNotPresent
    tag: ""  # Defaults to appVersion if not given
  imagePullSecrets: []
  # The number of SSHD replicas to use
  replicaCount: 1
  # Customise annotations for SSHD pods
  podAnnotations: {}
  # Customise pod-level security context for SSHD pods
  podSecurityContext:
    runAsNonRoot: true
  # Customise container-level security context for SSHD pods
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
  # The service definition for SSHD
  # Because SSH is a TCP service, it cannot be exposed with an Ingress
  # Instead, it must be exposed with a NodePort or LoadBalancer service
  service:
    type: LoadBalancer
    port: 22
    # Specify annotations for the service
    # annotations:
    # Use a fixed node port
    # nodePort: 32222
    # Use a fixed load-balancer IP
    # loadBalancerIP:
  # Resources for SSHD containers
  resources: {}
  # Customise node selector for SSHD pods
  nodeSelector: {}
  # Customise tolerations for SSHD pods
  tolerations: []
  # Customise affinity rules for SSHD pods
  affinity: {}


registrar:
  enabled: true
  # The registrar configuration
  config:
    baseDomain: "{{ pluck \"baseDomain\" .Values.common.ingress .Values.global.ingress | first }}"
    reservedSubdomains: []
  # The registrar ingress configuration
  ingress:
    # The subdomain that will be reserved for the registrar
    subdomain: registrar
  # The image to use for the registrar
  image:
    repository: ghcr.io/stackhpc/zenith-registrar
    pullPolicy: IfNotPresent
    tag: ""  # Defaults to appVersion if not given
  imagePullSecrets: []
  # The number of replicas to use
  replicaCount: 1
  # Customise annotations for pods
  podAnnotations: {}
  # Customise pod-level security context for registrar pods
  podSecurityContext:
    runAsNonRoot: true
  # Customise container-level security context for registrar pods
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true
  # Resources for containers
  resources: {}
  # Customise node selector for pods
  nodeSelector: {}
  # Customise tolerations for pods
  tolerations: []
  # Customise affinity rules for pods
  affinity: {}

metrics:
  enabled: false
  # Configuration for the dashboard
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
  # Configuration for the consul exporter
  consulExporter:
    # The image to use for the consul exporter
    # We use a synced version to avoid a dependency on Docker Hub
    image:
      repository: ghcr.io/stackhpc/zenith/consul-exporter
      pullPolicy: IfNotPresent
      tag: v0.9.0
    imagePullSecrets: []
    # The timeout for Consul queries used in the exporter
    # This is increased from the default to accomodate clusters with many services
    queryTimeout: 5s
    # Customise pod-level security context for consul exporter pods
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    # Customise container-level security context for consul exporter pods
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: true
    # Resources for consul exporter containers
    resources: {}
    # Customise annotations for consul exporter pods
    podAnnotations: {}
    # Customise node selector for consul exporter pods
    nodeSelector: {}
    # Customise tolerations for consul exporter pods
    tolerations: []
    # Customise affinity rules for consul exporter pods
    affinity: {}
  # Configuration for the Helm exporter
  helmExporter:
    # The image to use for the Helm exporter
    # We use a synced version to avoid a dependency on Docker Hub
    image:
      repository: ghcr.io/stackhpc/zenith/helm-exporter
      pullPolicy: IfNotPresent
      tag: 1.2.16
    imagePullSecrets: []
    # Customise pod-level security context for helm exporter pods
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    # Customise container-level security context for helm exporter pods
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: true
    # Resources for helm exporter containers
    resources: {}
    # Customise annotations for helm exporter pods
    podAnnotations: {}
    # Customise node selector for helm exporter pods
    nodeSelector: {}
    # Customise tolerations for helm exporter pods
    tolerations: []
    # Customise affinity rules for helm exporter pods
    affinity: {}
