apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith-operator.fullname" . }}
  labels: {{ include "zenith-operator.labels" . | nindent 4 }}
stringData:
  operator.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
