apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith-operator.fullname" . }}
  labels: {{ include "zenith-operator.labels" . | nindent 4 }}
stringData:
  # Use the appVersion as the default image tag
  operator.yaml: |
    {{-
      dict "defaultImageTag" .Chart.AppVersion |
        merge .Values.config |
        toYaml |
        nindent 4
    }}
