{{- if not .Values.kubeconfigSecret.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zenith-operator.fullname" . }}
  labels: {{ include "zenith-operator.labels" . | nindent 4 }}
{{- end }}
