apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zenith.fullname" . }}
  labels: {{ include "zenith.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "zenith.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "zenith.selectorLabels" . | nindent 8 }}
      annotations:
        # Force the deployment to roll when the config changes
        zenith.stackhpc.com/secret-etc-zenith-hash: {{ include (print $.Template.BasePath "/secret-etc-zenith.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.mitmProxy.enabled (eq .Values.mitmProxy.authInject.type "serviceaccount") }}
      serviceAccountName: {{ include "zenith.fullname" . }}
      {{- end }}
      containers:
        - name: zenith-client
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{
            printf "%s:%s"
              .Values.zenithClient.image.repository
              (default .Chart.AppVersion .Values.zenithClient.image.tag)
          }}
          imagePullPolicy: {{ .Values.zenithClient.image.pullPolicy }}
          resources: {{ toYaml .Values.zenithClient.resources | nindent 12 }}
          volumeMounts:
            - name: etc-zenith
              mountPath: /etc/zenith
              readOnly: true
            - name: tmp
              mountPath: /tmp
        {{- if .Values.mitmProxy.enabled }}
        - name: mitm-proxy
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{
            printf "%s:%s"
              .Values.mitmProxy.image.repository
              (default .Chart.AppVersion .Values.mitmProxy.image.tag)
          }}
          imagePullPolicy: {{ .Values.mitmProxy.image.pullPolicy }}
          env:
            - name: ZENITH_PROXY_LISTEN_PORT
              value: {{ .Values.mitmProxy.port | quote }}
            {{- with .Values.upstream.readTimeout }}
            - name: ZENITH_PROXY_READ_TIMEOUT
              value: {{ . | quote }}
            {{- end }}
            - name: ZENITH_PROXY_UPSTREAM_SCHEME
              value: {{ .Values.upstream.scheme }}
            - name: ZENITH_PROXY_UPSTREAM_HOST
              value: {{ .Values.upstream.host }}
            - name: ZENITH_PROXY_UPSTREAM_PORT
              value: {{ .Values.upstream.port | quote }}
            {{- with .Values.mitmProxy.authInject }}
            {{- if eq .type "basic" }}
            - name: ZENITH_PROXY_AUTH_INJECT
              value: basic
            - name: ZENITH_PROXY_AUTH_BASIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .basic.secretName | required "mitmProxy.authInject.basic.secretName is required" }}
                  key: {{ .basic.usernameKey }}
            - name: ZENITH_PROXY_AUTH_BASIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .basic.secretName }}
                  key: {{ .basic.passwordKey }}
            {{- else if eq .type "bearer" }}
            - name: ZENITH_PROXY_AUTH_INJECT
              value: bearer
            - name: ZENITH_PROXY_AUTH_BEARER_HEADER
              value: {{ .bearer.headerName | quote }}
            - name: ZENITH_PROXY_AUTH_BEARER_PREFIX
              value: {{ .bearer.headerPrefix | quote }}
            - name: ZENITH_PROXY_AUTH_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .bearer.secretName | required "mitmProxy.authInject.bearer.secretName is required" }}
                  key: {{ .bearer.tokenKey }}
            {{- else if eq .type "serviceaccount" }}
            - name: ZENITH_PROXY_AUTH_INJECT
              value: bearer
            - name: ZENITH_PROXY_AUTH_BEARER_TOKEN_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            {{- end }}
            {{- end }}
          resources: {{ toYaml .Values.mitmProxy.resources | nindent 12 }}
          volumeMounts:
            - name: var-cache-nginx
              mountPath: /var/cache/nginx
            - name: var-run-nginx
              mountPath: /var/run/nginx
        {{- end }}
      volumes:
        - name: etc-zenith
          secret:
            secretName: {{ include "zenith.fullname" . }}-etc-zenith
        - name: tmp
          emptyDir: {}
        {{- if .Values.mitmProxy.enabled }}
        - name: var-cache-nginx
          emptyDir: {}
        - name: var-run-nginx
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
