apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith.fullname" . }}-etc-zenith
  labels: {{ include "zenith.labels" . | nindent 4 }}
stringData:
  client.yaml: |
    {{- with .Values.zenithClient }}
    ssh_private_key_data: {{ .sshPrivateKeyData | required "zenithClient.sshPrivateKeyData is required" | quote }}
    server_address: {{ .server.host | required "zenithClient.server.host is required" }}
    server_port: {{ .server.port }}
    skip_auth: {{ .auth.skip | toYaml }}
    auth_params: {{ .auth.params | toYaml | nindent 6 }}
    {{- end }}

    {{- if .Values.mitmProxy.enabled }}
    forward_to_host: 127.0.0.1
    forward_to_port: {{ .Values.mitmProxy.port }}
    backend_protocol: http
    {{- else }}
    forward_to_host: {{ .Values.upstream.host | required "upstream.host is required" }}
    forward_to_port: {{ .Values.upstream.port | required "upstream.port is required" }}
    backend_protocol: {{ .Values.upstream.scheme }}
    {{- end }}
    {{- with .Values.upstream.readTimeout }}
    read_timeout: {{ . }}
    {{- end }}
