{{- if .Values.mitmProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith.fullname" . }}-etc-nginx-confd
  labels: {{ include "zenith.labels" . | nindent 4 }}
stringData:
  upstream.conf: |
    include /etc/nginx/includes/websockets.conf;

    server {
        listen       127.0.0.1:{{ .Values.mitmProxy.port }};
        server_name  _;

        include /etc/nginx/includes/proxy.conf;

        {{- with .Values.upstream.readTimeout }}
        proxy_read_timeout: {{ . }}s;
        {{- end }}

        location / {
            {{- with .Values.upstream }}
            proxy_pass {{ .scheme }}://{{ .host | required "upstream.host is required" }}:{{ .port | required "upstream.port is required" }};
            {{- end }}
        }
    }
{{- end }}
