apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith.fullname" . }}
  labels: {{ include "zenith.labels" . | nindent 4 }}
data:
  client.yaml: |
    ssh_private_key_data: {{ .Values.sshPrivateKeyData | required "sshPrivateKeyData is required" | quote }}
    server_address: {{ .Values.server.host | required "server.host is required" }}
    server_port: {{ .Values.server.port }}
    forward_to_host: {{ .Values.upstream.host }}
    forward_to_port: {{ .Values.upstream.port }}
    backend_protocol: {{ .Values.upstream.protocol }}
    {{- with .Values.upstream.readTimeout }}
    read_timeout: {{ . }}
    {{- end }}
    skip_auth: {{ .Values.auth.skip | toYaml }}
    auth_params: {{ .Values.auth.params | toYaml | nindent 6 }}
