# The base64-encoded SSH private key data for the client
# The SSH key should already be associated with a Zenith subdomain
sshPrivateKeyData:

# Configuration for the Zenith server
server:
  host:
  port: 22

# Configuration for the upstream that is being proxied
upstream:
  host: 127.0.0.1
  port: 8000
  # One of http or https
  protocol: http
  # Read timeout in seconds, or leave blank for default
  readTimeout:

# Auth configuration for the Zenith proxy
auth:
  # Indicates whether to apply authentication for the service
  skip: false
  # Authentication parameters to be used by the Zenith auth callout
  # Available parameters will depend on the configuration of the target Zenith server
  params: {}

# The image to use for the operator
image:
  repository: ghcr.io/stackhpc/zenith-client
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to appVersion if not given

imagePullSecrets: []

# The number of replicas to use
replicaCount: 1

# Pod-level security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

# Container-level security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

# Resource requests and limits for the containers
resources: {}

# Node selector for operator pods
nodeSelector: {}

# Affinity rules for operator pods
affinity: {}

# Tolerations for operator pods
tolerations: []
