# Configuration for the upstream that is being proxied
upstream:
  host:
  port:
  # One of http or https
  scheme: http
  # Read timeout in seconds, or leave blank for default
  readTimeout:

# Configuration for the Zenith client
zenithClient:
  # The base64-encoded SSH private key data for the client
  # The SSH key should already be associated with a Zenith subdomain
  sshPrivateKeyData:
  # Configuration for the Zenith server
  server:
    host:
    port: 22
  # Auth configuration for the Zenith proxy
  auth:
    # Indicates whether to apply authentication for the service
    skip: false
    # Authentication parameters to be used by the Zenith auth callout
    # Available parameters will depend on the configuration of the target Zenith server
    params: {}
  # The image to use for the Zenith client container
  image:
    repository: ghcr.io/stackhpc/zenith-client
    pullPolicy: IfNotPresent
    tag: ""  # Defaults to appVersion if not given
  # Resource requests and limits for the Zenith client container
  resources: {}

mitmProxy:
  enabled: true
  # The port that the proxy is listening on
  # It should listen to localhost only on plain http
  port: 8080
  # The authentication parameters to inject
  authInject:
    # Can be basic, bearer, serviceaccount or none
    type: none
    # Options for basic authentication
    basic:
      # The name of the secret containing basic auth credentials
      secretName:
      # The key of the username within the secret
      usernameKey: username
      # The key of the password within the secret
      passwordKey: password
    # Options for bearer token authentication
    bearer:
      # The name of the secret containing the bearer token
      secretName:
      # The key of the bearer token within the secret
      tokenKey: token
      # The name of the header to use for the token
      headerName: Authorization
      # The prefix to add to the header value
      headerPrefix: Bearer
    # Options for service account authentication
    serviceAccount:
      # The cluster role to bind the service account to
      clusterRoleName: cluster-admin
  # The image to use for the proxy container
  image:
    repository: ghcr.io/stackhpc/zenith-proxy
    pullPolicy: IfNotPresent
    tag: ""  # Defaults to appVersion if not given
  # Resource requests and limits for the proxy container
  resources: {}

imagePullSecrets: []

# The number of replicas to use
replicaCount: 1

# Pod-level security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

# Container-level security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

# Node selector for operator pods
nodeSelector: {}

# Affinity rules for operator pods
affinity: {}

# Tolerations for operator pods
tolerations: []
