apiVersion: v2
name: zenith-client
description: Helm chart for deploying a Zenith client on Kubernetes
type: application
# The version and appVersion are updated by the chart build script
version: 0.1.0
appVersion: main
