{{- define "zenith.sshd.defaults" -}}
# Use the internal service for the registrar
registrarUrl: http://{{ include "zenith.componentname" (list . "registrar") }}
{{- end }}

{{- if .Values.sshd.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zenith.componentname" (list . "sshd-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "sshd-conf") | nindent 4 }}
data:
  user-config.yaml: |
    {{-
      tpl (toYaml .Values.sshd.config) . |
        fromYaml |
        mergeOverwrite (include "zenith.sshd.defaults" . | fromYaml) |
        toYaml |
        nindent 4
    }}
{{- end }}
