{{- if .Values.sshd.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zenith.componentname" (list . "sshd") }}
  labels: {{ include "zenith.componentLabels" (list . "sshd") | nindent 4 }}
  namespace: {{ .Values.common.kubernetes.targetNamespace }}
rules:
  - apiGroups:
      - zenith.stackhpc.com
    resources:
      - services
    verbs:
      - get
  - apiGroups:
      - zenith.stackhpc.com
    resources:
      - endpoints
    verbs:
      - get
      - list
      - create
      - patch
  - apiGroups:
      - zenith.stackhpc.com
    resources:
      - leases
    verbs:
      - create
      - patch
      - delete
  - apiGroups:
      - zenith.stackhpc.com
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
{{- end }}
