{{- if .Values.sshd.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zenith.componentname" (list . "sshd") }}
  labels: {{ include "zenith.componentLabels" (list . "sshd") | nindent 4 }}
{{- end }}
