{{- define "zenith.registrar.defaults" -}}
reservedSubdomains: {{
  .Values.common.reservedSubdomains |
    concat (default list .Values.registrar.config.reservedSubdomains) |
    concat (list .Values.common.ingress.registrarSubdomain) |
    toYaml |
    nindent 2
}}
consulAddress: {{ tpl .Values.common.consul.address . | quote }}
consulPort: {{ .Values.common.consul.port }}
consulKeyPrefix: {{ .Values.common.consul.registrarKeyPrefix | quote }}
{{- end }}

{{- if .Values.registrar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith.componentname" (list . "registrar-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "registrar-conf") | nindent 4 }}
stringData:
  registrar.yaml: |
    {{-
      include "zenith.registrar.defaults" . |
        fromYaml |
        merge (omit .Values.registrar.config "reservedSubdomains") |
        toYaml |
        nindent 4
    }}
{{- end }}
