{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "zenith.componentname" (list . "consul-exporter") }}
  labels: {{ include "zenith.componentLabels" (list . "consul-exporter") | nindent 4 }}
spec:
  groups:
    - name: consul
      rules:
        - alert: ConsulDown
          expr: min(consul_up) == 0
          for: 15m
          annotations:
            description: Consul has been reporting as down for more than 15 minutes.
            summary: Consul has been reporting as down for more than 15 minutes.
          labels:
            severity: warning

        - alert: ConsulNodeUnhealthy
          expr: sum(consul_health_node_status{status!="passing"}) by (node) > 0
          for: 15m
          annotations:
            description: >-
              Consul node {{ "{{" }} $labels.node {{ "}}" }} has been unhealthy for more than 15 minutes.
            summary: Consul node has been unhealthy for more than 15 minutes.
          labels:
            severity: warning
{{- end }}
