apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "zenith-service.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: dynamic
