{{- $component := "proxy" -}}
{{- $values := get .Values $component -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tunnel-proxy.componentname" (list . $component) }}
  labels: {{ include "tunnel-proxy.componentLabels" (list . $component) | nindent 4 }}
spec:
  replicas: {{ $values.replicaCount }}
  selector:
    matchLabels: {{ include "tunnel-proxy.componentSelectorLabels" (list . $component) | nindent 6 }}
  template:
    metadata:
      labels: {{ include "tunnel-proxy.componentSelectorLabels" (list . $component) | nindent 8 }}
      {{- with $values.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml $values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $component }}
          securityContext: {{ toYaml $values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" $values.image.repository (tpl $values.image.tag .) }}
          imagePullPolicy: {{ $values.image.pullPolicy }}
          env:
            - name: PROXY_BASE_DOMAIN
              value: {{ $values.baseDomain | required "proxy.baseDomain is required" | quote }}
            # For the proxy, contact Consul using the load-balanced cluster service
            - name: CONSUL_HTTP_ADDR
              value: {{ include "consul.fullname" . | printf "%s-server:8500" | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_health
              port: http
          readinessProbe:
            httpGet:
              path: /_health
              port: http
          resources: {{ toYaml $values.resources | nindent 12 }}
          volumeMounts:
            - name: var-cache-nginx
              mountPath: /var/cache/nginx
            - name: var-run-nginx
              mountPath: /var/run/nginx
      {{- with $values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: var-cache-nginx
          emptyDir: {}
        - name: var-run-nginx
          emptyDir: {}
