{{- if .Values.sshd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zenith.componentname" (list . "sshd-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "sshd-conf") | nindent 4 }}
data:
  sshd.yaml: |
    {{- tpl (toYaml .Values.sshd.config) . | nindent 4 }}
{{- end }}
