apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zenith.componentname" (list . "sshd") }}
  labels: {{ include "zenith.componentLabels" (list . "sshd") | nindent 4 }}
spec:
  replicas: {{ .Values.sshd.replicaCount }}
  selector:
    matchLabels: {{ include "zenith.componentSelectorLabels" (list . "sshd") | nindent 6 }}
  template:
    metadata:
      labels: {{ include "zenith.componentSelectorLabels" (list . "sshd") | nindent 8 }}
      {{- with .Values.sshd.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.sshd.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml .Values.sshd.podSecurityContext | nindent 8 }}
      containers:
        - name: sshd
          securityContext: {{ toYaml .Values.sshd.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.sshd.image.repository (default .Chart.AppVersion .Values.sshd.image.tag) }}
          imagePullPolicy: {{ .Values.sshd.image.pullPolicy }}
          env:
            {{- if not .Values.sshd.config.consulAddress }}
            # If a Consul agent address is not explicitly specified, we will attempt to connect
            # to an agent running on the host (as deployed by the Consul Helm chart)
            - name: ZENITH_SSHD__CONSUL_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- end }}
            # The pod IP should ALWAYS be used as the service host in Consul, even if service
            # host is specified in the configuration
            - name: ZENITH_SSHD__SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: sshd
              containerPort: 2222
              protocol: TCP
          resources: {{ toYaml .Values.sshd.resources | nindent 12 }}
          volumeMounts:
            - name: etc-zenith
              mountPath: /etc/zenith
              readOnly: true
            - name: var-run-sshd
              mountPath: /var/run/sshd
      {{- with .Values.sshd.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sshd.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sshd.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: etc-zenith
          configMap:
            name: {{ include "zenith.componentname" (list . "sshd-conf") }}
        - name: var-run-sshd
          emptyDir: {}
