{{- if .Values.sshd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zenith.componentname" (list . "sshd") }}
  labels: {{ include "zenith.componentLabels" (list . "sshd") | nindent 4 }}
  {{- with .Values.sshd.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.sshd.service.type }}
  {{- with .Values.sshd.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - name: sshd
      port: {{ .Values.sshd.service.port }}
      targetPort: sshd
      protocol: TCP
      {{- with .Values.sshd.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector: {{ include "zenith.componentSelectorLabels" (list . "sshd") | nindent 4 }}
{{- end }}
