[project]
name = "zenith-sync"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.14.3",
    "click>=8.5.0",
    "configomatic[yaml]>=0.4.0",
    "easykube>=0.6.0",
    "easysemver>=0.2.0",
    "httpx>=0.28.1",
    "kube-custom-resource>=0.6.1",
    "pydantic<3",
    "pyhelm3>=0.5.5",
    "pyyaml>=6.0.3",
]

[project.scripts]
zenith-sync = "zenith.sync.cli:main"

[project.entry-points."zenith.sync.processors"]
helm = "zenith.sync.processor.helm:Processor"

[project.entry-points."zenith.sync.stores"]
consul = "zenith.sync.store.consul:Store"
crd    = "zenith.sync.store.crd:Store"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.1+unknown"

[tool.hatch.build.targets.sdist]
packages = ["zenith"]
[tool.hatch.build.targets.wheel]
packages = ["zenith"]
