{{- if .Values.sync.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zenith.componentname" (list . "sync") }}
  labels: {{ include "zenith.componentLabels" (list . "sync") | nindent 4 }}
rules:
  # The sync process needs to be able to query ingress classes, which are cluster-scoped
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list"]
{{- end }}
