{{- define "zenith.sync.defaults" -}}
{{- $global := deepCopy .Values.global.ingress }}
{{- $common := deepCopy .Values.common.ingress }}
{{- $ingress := mergeOverwrite $global $common }}
consul:
  address: {{ tpl .Values.common.consul.address . | quote }}
  port: {{ .Values.common.consul.port }}
  serviceTag: {{ .Values.common.consul.serviceTag | quote }}
  tlsKeyPrefix: {{ .Values.common.consul.serviceKeyPrefix | quote }}
kubernetes:
  ingress:
    baseDomain: {{ $ingress.baseDomain | quote }}
    className: {{ $ingress.className | quote }}
    annotations: {{ $ingress.annotations | toYaml | nindent 6 }}
    tls:
      enabled: {{ $ingress.tls.enabled }}
      {{- with $ingress.tls.secretName }}
      secretName: {{ . | quote }}
      {{- end }}
{{- end }}

{{- if .Values.sync.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zenith.componentname" (list . "sync-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "sync-conf") | nindent 4 }}
data:
  sync.yaml: |
    {{-
      tpl (toYaml .Values.sync.config) . |
        fromYaml |
        mergeOverwrite (include "zenith.sync.defaults" . | fromYaml) |
        toYaml |
        nindent 4
    }}
{{- end }}
