{{- define "zenith.sync.defaults" -}}
consul:
  address: {{ tpl .Values.common.consul.address . | quote }}
  port: {{ .Values.common.consul.port }}
  serviceTag: {{ .Values.common.consul.serviceTag | quote }}
  tlsKeyPrefix: {{ .Values.common.consul.serviceKeyPrefix | quote }}
kubernetes:
  ingress:
    baseDomain: {{ .Values.common.ingress.baseDomain | quote }}
    className: {{ .Values.common.ingress.className | quote }}
    annotations: {{ .Values.common.ingress.annotations | toYaml | nindent 6 }}
    tls:
      enabled: {{ .Values.common.ingress.tls.enabled }}
      {{- with .Values.common.ingress.tls.secretName }}
      secretName: {{ . | quote }}
      {{- end }}
{{- end }}

{{- if .Values.sync.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zenith.componentname" (list . "sync-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "sync-conf") | nindent 4 }}
data:
  sync.yaml: |
    {{-
      include "zenith.sync.defaults" . |
        fromYaml |
        merge .Values.sync.config |
        toYaml |
        nindent 4
    }}
{{- end }}
