{{- if .Values.sync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zenith.componentname" (list . "sync-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "sync-conf") | nindent 4 }}
data:
  sync.yaml: |
    {{- $fromGlobals := dict "kubernetes" (dict "ingress" (default dict .Values.global.ingress)) }}
    {{- $config := tpl (toYaml .Values.sync.config) . | fromYaml | mergeOverwrite $fromGlobals }}
    {{- if $config.kubernetes.ingress.baseDomain }}
    {{- toYaml $config | nindent 4 }}
    {{- else }}
    {{- fail "sync.config.kubernetes.ingress.baseDomain is required" }}
    {{- end }}
{{- end }}
