apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zenith.componentname" (list . "sync-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "sync-conf") | nindent 4 }}
data:
  sync.yaml: |
    {{- if .Values.sync.config.kubernetes.ingress.baseDomain }}
    {{- tpl (toYaml .Values.sync.config) . | nindent 4 }}
    {{- else }}
    {{- fail "baseDomain is required" }}
    {{- end }}
