{{- if .Values.sync.enabled }}
# This role allows the holder to manage Zenith services in the target namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zenith.componentname" (list . "sync") }}-manage-crds
  labels: {{ include "zenith.componentLabels" (list . "sync") | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - endpoints.zenith.stackhpc.com
      - services.zenith.stackhpc.com
    verbs:
      - update
      - patch
{{- end }}
