{{- define "zenith.sync.defaults" -}}
{{- $global := deepCopy .Values.global.ingress }}
{{- $common := deepCopy .Values.common.ingress }}
{{- $ingress := mergeOverwrite $global $common }}
kubernetes:
  targetNamespace: {{ .Values.common.kubernetes.targetNamespace }}
  # By default, we use the same chart version for the service chart
  serviceChartVersion: {{ .Chart.Version }}
  ingress:
    baseDomain: {{ $ingress.baseDomain | quote }}
    subdomainAsPathPrefix: {{ $ingress.subdomainAsPathPrefix }}
    className: {{ $ingress.className | quote }}
    annotations: {{ $ingress.annotations | toYaml | nindent 6 }}
    tls:
      enabled: {{ $ingress.tls.enabled }}
      terminatedAtProxy: {{ $ingress.tls.terminatedAtProxy }}
      {{- with $ingress.tls.secretName }}
      secretName: {{ . | quote }}
      {{- end }}
      annotations: {{ $ingress.tls.annotations | toYaml | nindent 8 }}
{{- end }}

{{- if .Values.sync.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zenith.componentname" (list . "sync-conf") }}
  labels: {{ include "zenith.componentLabels" (list . "sync-conf") | nindent 4 }}
data:
  sync.yaml: |
    {{-
      tpl (toYaml .Values.sync.config) . |
        fromYaml |
        mergeOverwrite (include "zenith.sync.defaults" . | fromYaml) |
        toYaml |
        nindent 4
    }}
{{- end }}
