{{- if .Values.sync.enabled }}
# This role allows the holder to manage Zenith services in the target namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zenith.componentname" (list . "sync") }}-manage-services
  labels: {{ include "zenith.componentLabels" (list . "sync") | nindent 4 }}
  namespace: {{ .Values.common.kubernetes.targetNamespace }}
rules:
  # Permissions for the CRD store
  - apiGroups:
      - zenith.stackhpc.com
    resources:
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - zenith.stackhpc.com
    resources:
      - endpoints
    verbs:
      - list
      - get
      - watch
      - patch
  - apiGroups:
      - zenith.stackhpc.com
    resources:
      - leases
    verbs:
      - list
      - patch
      - delete
  # Permissions for the Helm processor
  # For basic services, we need to manage:
  #   * secrets
  #   * endpoints (removing for legacy services)
  #   * endpointslices
  #   * services
  #   * ingresses
  # For OIDC authenticated services, we also need to manage:
  #   * configmaps
  #   * deployments
  #   * poddisruptionbudgets
  #   * serviceaccounts
  #   * servicemonitors
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - secrets
      - services
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - "*"
{{- end }}
