{{- if and .Values.sync.enabled .Values.common.trustBundle }}
# This role binding allows the sync service account to access the trust bundle configmap
# in the release namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zenith.componentname" (list . "sync") }}-trust-bundle-reader
  labels: {{ include "zenith.componentLabels" (list . "sync") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "zenith.componentname" (list . "sync") }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "zenith.componentname" (list . "sync") }}-trust-bundle-reader
{{- end }}
