{{- if .Values.sync.enabled }}
# This role allows the holder to manage Zenith services in the target namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zenith.componentname" (list . "sync") }}-manage-services
  labels: {{ include "zenith.componentLabels" (list . "sync") | nindent 4 }}
  namespace: {{ .Values.sync.config.kubernetes.targetNamespace }}
rules:
  # For basic services, we need to manage secrets, endpoints, services and ingresses
  # For OIDC authenticated services, we also need to manage configmaps, deployments,
  # poddisruptionbudgets, serviceaccounts and servicemonitors
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - secrets
      - services
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - "*"
{{- end }}
