{{- if and .Values.sync.enabled .Values.common.trustBundle }}
# This role allows the holder to read the trust bundle configmap in the release namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zenith.componentname" (list . "sync") }}-trust-bundle-reader
  labels: {{ include "zenith.componentLabels" (list . "sync") | nindent 4 }}
rules:
  # We only need access to the named configmap
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ include "zenith.componentname" (list . "trust-bundle") }}
    verbs:
      - list
      - get
      - watch
{{- end }}
