{{- if .Values.sync.enabled }}
# This role binding allows the sync service account in the release namespace
# to manage Zenith services in the target namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zenith.componentname" (list . "sync") }}-manage-services
  labels: {{ include "zenith.componentLabels" (list . "sync") | nindent 4 }}
  namespace: {{ .Values.sync.config.kubernetes.targetNamespace }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "zenith.componentname" (list . "sync") }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "zenith.componentname" (list . "sync") }}-manage-services
{{- end }}
