{{- range .Values.endpoints }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ printf "%s-%s" $.Release.Name .id }}
  labels:
    {{- include "zenith-service.labels" $ | nindent 4 }}
    kubernetes.io/service-name: {{ $.Release.Name }}
addressType: IPv4
ports:
  - name: dynamic
    protocol: TCP
    port: {{ .port }}
endpoints:
  - addresses:
      - {{ .address }}
    conditions:
      ready: true
{{- end }}
