{{-
  if and
    .Values.oidc.enabled
    (not .Values.oidc.ingress.enabled)
}}
{{- $ingressTLSRequired := and .Values.global.secure (not .Values.ingress.tls.terminatedAtProxy) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-oidc
  labels: {{ include "zenith-service.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- if $ingressTLSRequired }}
    {{- if not .Values.ingress.tls.existingCertificate.cert }}
    {{- with .Values.ingress.tls.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if $ingressTLSRequired }}
  tls:
    - hosts:
        - {{ include "zenith-service.ingress.host" . }}
      secretName: {{ include "zenith-service.ingress.tls.secretName" . }}
  {{- end }}
  rules:
    - host: {{ include "zenith-service.ingress.host" . }}
      http:
        paths:
          - path: {{ tpl (index .Values.oidc.extraArgs "proxy-prefix") . }}
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-oidc" .Release.Name }}
                port:
                  name: http
{{- end }}
