{{-
  if and
    (mustRegexMatch "^https?$" .Values.protocol)
    .Values.ingress.enabled
    (eq .Values.ingress.routingType "ingressroute")
}}
{{- $host := include "zenith-service.ingress.host" . }}
{{- $path := include "zenith-service.ingress.pathPrefix" . }}
{{- $secure := and .Values.global.secure (not .Values.ingress.tls.terminatedAtProxy) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "zenith-service.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ if .Values.global.secure }}websecure{{ else }}web{{ end }}
  routes:
    - match: Host(`{{ $host }}`) && PathPrefix(`{{ $path }}`)
      kind: Rule
      {{- if .Values.oidc.enabled }}
      middlewares:
        - name: {{ .Release.Name }}-oidc-auth
      {{- end }}
      services:
        - name: {{ .Release.Name }}
          port: dynamic
  {{- if $secure }}
  tls:
    secretName: {{ include "zenith-service.ingress.tls.secretName" . }}
  {{- end }}
{{- end }}
