{{-
  if and
    .Values.global.secure
    .Values.ingress.tls.clientCA
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith-service.ingress.tls.clientCASecretName" . }}
  labels: {{ include "zenith-service.labels" . | nindent 4 }}
data:
  ca.crt: |
    {{- .Values.ingress.tls.clientCA | nindent 4 }}
{{- end }}
