{{-
  if and
    .Values.global.secure
    (not .Values.ingress.tls.terminatedAtProxy)
    .Values.ingress.tls.existingCertificate.cert
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith-service.ingress.tls.secretName" . }}
  labels: {{ include "zenith-service.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{- .Values.ingress.tls.existingCertificate.cert | nindent 4 }}
  tls.key: |
    {{-
      .Values.ingress.tls.existingCertificate.key |
        required "key is required if certificate is given" |
        nindent 4
    }}
{{- end }}
