apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "zenith-service.labels" . | nindent 4 }}
spec:
  ports:
    - name: dynamic
      protocol: TCP
      {{- if eq .Values.protocol "http" }}
      port: 80
      {{- else if eq .Values.protocol "https" }}
      port: 443
      {{- else if eq .Values.protocol "ssh" }}
      port: 22
      {{- else }}
      {{- fail "unsupported protocol" }}
      {{- end }}
      targetPort: dynamic
