[project]
name = "zenith-operator"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "configomatic[yaml]>=0.4.0",
    "cryptography>=50.0.1",
    "easykube>=0.6.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "kopf>=1.44.6",
    "kube-custom-resource>=0.6.1",
    "pydantic<3",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
    "black~=26.5.1",
    "codespell>=2.4.3",
    "coverage!=4.4,>=7.15.0",
    "mypy>=2.3.1",
    "python-subunit>=1.4.6",
    "ruff>=0.15.20",
    "stestr>=4.2.1",
    "testtools>=2.9.1",
    "types-pyyaml>=6.0.12.20260906",
    "types-setuptools>=84.0.0.20260812",
    "tox>=4.61.2",
    "tox-uv>=1.36.0",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.1+unknown"

[tool.hatch.build.targets.sdist]
packages = ["operator"]
[tool.hatch.build.targets.wheel]
packages = ["operator"]
