[tox]
minversion = 4.0.0
# We run autofix last, to ensure CI fails,
# even though we do our best to autofix locally
envlist = py,ruff,codespell,autofix
# TODO: fix mypy and add to envlist
skipsdist = True

[testenv]
runner = uv-venv-lock-runner
setenv =
   PYTHONWARNINGS=default::DeprecationWarning
commands = pytest {posargs}

[testenv:autofix]
commands =
    ruff format {tox_root}
    codespell {tox_root} -w
    ruff check {tox_root} --fix

[testenv:black]
# TODO: understand why ruff doesn't fix
# line lengths as well as black does
commands = black {tox_root} {posargs}

[testenv:codespell]
commands = codespell {posargs}

[testenv:ruff]
description = Run Ruff checks
commands =
    ruff check {tox_root}
    ruff format {tox_root} --check

[testenv:venv]
commands = {posargs}

[testenv:cover]
commands =
    pytest --cov=zenith.operator --cov-report=html:cover --cov-report=xml:cover/coverage.xml --cov-report=term {posargs}

[testenv:mypy]
commands = mypy {tox_root} {posargs}
