apiVersion: v1
kind: Secret
metadata:
  name: {{ name }}-zenith-client
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/managed-by: zenith-operator
    {{ settings.api_group }}/client: {{ name }}
stringData:
  client.yaml: |
    ssh_private_key_data: {{ ssh_private_key_data }}

    server_address: {{ settings.sshd_host }}
    server_port: {{ settings.sshd_port }}
    
    skip_auth: {{ "true" if client.spec.auth.skip else "false" }}
    auth_type: {{ client.spec.auth.type | default(settings.default_auth_type, true) | attr("value") }}

{%- if client.spec.auth.oidc %}
    auth_oidc_issuer: {{ client.spec.auth.oidc.issuer }}
{%- elif settings.default_oidc_issuer %}
    auth_oidc_issuer: {{ settings.default_oidc_issuer }}
{%- if settings.default_oidc_client_registration_token %}
    auth_oidc_client_registration_token: {{ settings.default_oidc_client_registration_token }}
{%- endif %}
{%- endif %}

{%- set default_params = settings.default_external_auth_params %}
{%- set client_params = client.spec.auth.external.params | default({}, true) %}
    auth_external_params:
      {{ default_params | mergeconcat(client_params) | toyaml | indent(6) }}

{%- if client.spec.mitm_proxy.enabled %}
    forward_to_host: 127.0.0.1
    forward_to_port: {{ client.spec.mitm_proxy.port }}
    backend_protocol: http
{%- else %}
    forward_to_host: {{ upstream_host }}
    forward_to_port: {{ upstream_port }}
    backend_protocol: {{ client.spec.upstream.scheme }}
{%- endif %}
{%- if client.spec.upstream.read_timeout %}
    read_timeout: {{ client.spec.upstream.read_timeout }}
{%- endif %}
