apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ name }}-zenith-client
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/managed-by: zenith-operator
    {{ settings.api_group }}/client: {{ name }}
