name: Publish artifacts
# Run the tasks on every push
on: push
jobs:
  # build_push_images:
  #   name: Build and push images
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - component: client
  #         - component: sshd
  #         - component: sync
  #   steps:
  #     - name: Check out the repository
  #       uses: actions/checkout@v2

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #       with:
  #         platforms: all

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Set up Docker layer caching
  #       uses: actions/cache@v2
  #       with:
  #         path: /tmp/.buildx-cache
  #         key: ${{ runner.os }}-buildx-${{ matrix.component }}-${{ github.sha }}
  #         restore-keys: |
  #           ${{ runner.os }}-buildx-${{ matrix.component }}-

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Calculate metadata for image
  #       id: image-meta
  #       uses: docker/metadata-action@v3
  #       with:
  #         images: ghcr.io/stackhpc/zenith-${{ matrix.component }}
  #         # Produce the branch name or tag and the SHA as tags
  #         tags: |
  #           type=ref,event=branch
  #           type=ref,event=tag
  #           type=sha,prefix=

  #     - name: Build and push image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./${{ matrix.component }}
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ${{ steps.image-meta.outputs.tags }}
  #         labels: ${{ steps.image-meta.outputs.labels }}
  #         cache-from: type=local,src=/tmp/.buildx-cache
  #         cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

  #     # Temp fix
  #     # https://github.com/docker/build-push-action/issues/252
  #     # https://github.com/moby/buildkit/issues/1896
  #     # https://github.com/docker/buildx/pull/535
  #     - name: Move cache
  #       run: |
  #         rm -rf /tmp/.buildx-cache
  #         mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build_push_chart:
    name: Build and push Helm chart
    runs-on: ubuntu-latest
    # Only build and push the chart if the images built successfully
    # needs: [build_push_images]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          # This is important for the semver action to work correctly
          # when determining the number of commits since the last tag
          fetch-depth: 0

      - name: Get SemVer version for current commit
        id: semver
        uses: ./.github/actions/semver-action

      - name: Publish Helm charts
        run: ./.github/actions/helm-publish-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.semver.outputs.version }}
          app-version: ${{ steps.semver.outputs.short-sha }}

      # Use an up-to-date version of Python for the script
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.9

      # # This action packages and pushes the chart
      # - name: Publish charts
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: ./ci/publish-charts.py
